[package]
name = "benches"
version.workspace = true
edition = "2021"
publish = false


[dev-dependencies]
pulz-ecs.workspace = true 
bevy_ecs = "0.16"

criterion = { version = "0.7", features = [ "html_reports" ] }

[[bench]]
name = "ecs_world"
harness = false
