[package]
name = "benches"
version = "0.1.0"
edition = "2021"
publish = false


[dev-dependencies]
pulz-ecs = { path = "../crates/ecs" }
bevy_ecs = "0.17"

criterion = { version = "0.7", features = [ "html_reports" ] }

[[bench]]
name = "ecs_world"
harness = false
